### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by vjpr** [int0h/npm-hddSpace#1]
```
  TypeError: func is not a function
      at getCrossPlatformInfo (xxx/node_modules/hdd-space/hddSpace.js:113:2)
      at settings.js:77:44
      at Promise.F (xxx/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
      at _callee3$ (settings.js:77:27)
      at tryCatch (xxx/node_modules/babel-runtime/regenerator/runtime.js:72:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (xxx/node_modules/babel-runtime/regenerator/runtime.js:334:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (xxx/node_modules/babel-runtime/regenerator/runtime.js:105:21)
      at step (xxx/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at xxx/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
```

**Comment by int0h** [comment]
Hello! Thanks for feedback! I updated the repo and npm. I also checked it on a mac. Everything should work now. Let me know if that help you or not :)
